### ISSUE TITLE
📃 벌금 장부

### ISSUE THREAD

**Issue by yesyeseo** [yesyeseo/Golang-Study#6]
|회차|날짜|김윤서|김선영|김하연|장예서|
|---|---|:---:|:---:|:---:|:---:|
|01|21.10.13|`1000`|`1000`| |
|02|21.11.03|`3000`|`1000`| |
|03|21.11.10|`1000`|
|04|21.11.17| | | `1000` | `3000` |
|05|21.11.24| `1000` | | | `3000` |
|06|21.12.01| | `3000` | | `3000` |
|08|21.12.29| `6000` ✔️ | `3000` | `3000` ✔️ | `3000` ✔️ |
|09|22.01.05|`1000` | `3000` ✔️ | | |
|10|22.01.12| `1000` | | | `3000` |
|11|22.01.19|`3000` | `3000` | | |
|12|22.01.26|`3000` | `3000` | | |
|13|22.02.02|`3000` | `3000` | | `3000`|

**Comment by ottl-seo** [comment]
벌금 벌써 오천원 쌓인 사람 접니다... :)
